In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.float_format = '{:,.1f}'.format

In [3]:
np.set_printoptions(precision=2)

In [4]:
np.random.rand()

0.4196884965365828

In [7]:
np.random.randn()

-0.3783259921491686

In [13]:
x1 = np.random.rand(2,5)*10  #2 filas x 5 columnas
x1


array([[5.08, 5.37, 3.58, 3.11, 4.73],
       [9.19, 9.62, 6.2 , 4.75, 0.56]])

In [11]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.2 , -0.14, -0.9 , -0.78, -0.92],
       [-0.54, -0.72, -0.58, -0.98, -0.72]])

In [14]:
np.concatenate([x1, x2]) #concatenando a lo largo de las filas

array([[ 5.08,  5.37,  3.58,  3.11,  4.73],
       [ 9.19,  9.62,  6.2 ,  4.75,  0.56],
       [-0.2 , -0.14, -0.9 , -0.78, -0.92],
       [-0.54, -0.72, -0.58, -0.98, -0.72]])

In [15]:
np.concatenate([x1, x2]).shape

(4, 5)

In [19]:
np.concatenate([x1, x2], axis=1) # concatc por columnas

array([[ 5.08,  5.37,  3.58,  3.11,  4.73, -0.2 , -0.14, -0.9 , -0.78,
        -0.92],
       [ 9.19,  9.62,  6.2 ,  4.75,  0.56, -0.54, -0.72, -0.58, -0.98,
        -0.72]])

In [18]:
np.concatenate([x1, x2], axis=1).shape

(2, 10)

In [21]:
s1 = pd.Series(x1[0], index=['a', 'b', 'c', 'd', 'e'])
s1

a   5.1
b   5.4
c   3.6
d   3.1
e   4.7
dtype: float64

In [23]:
s2 = pd.Series(x2[0], index=['c', 'd', 'e', 'f', 'g'])
s2

c   -0.2
d   -0.1
e   -0.9
f   -0.8
g   -0.9
dtype: float64

In [26]:
pd.concat([s1, s2]) #por las filas

a    5.1
b    5.4
c    3.6
d    3.1
e    4.7
c   -0.2
d   -0.1
e   -0.9
f   -0.8
g   -0.9
dtype: float64

In [27]:
pd.concat([s1, s2], axis=1) #por columnas compartiendo indices repetidos

0    1
a 5.1  NaN
b 5.4  NaN
c 3.6 -0.2
d 3.1 -0.1
e 4.7 -0.9
f NaN -0.8
g NaN -0.9

In [28]:
s1.reset_index()

index   0
0     a 5.1
1     b 5.4
2     c 3.6
3     d 3.1
4     e 4.7

In [29]:
s1.reset_index(drop=True)

0   5.1
1   5.4
2   3.6
3   3.1
4   4.7
dtype: float64

In [31]:
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0    1
0 5.1 -0.2
1 5.4 -0.1
2 3.6 -0.9
3 3.1 -0.8
4 4.7 -0.9

In [34]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a', 'b'])
df1

a   b
0 8.2 9.7
1 6.7 4.1
2 8.2 5.6

In [35]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a', 'b'], index=[2,3,4])
df2

a    b
2 -0.1 -0.6
3 -0.2 -0.6
4 -0.3 -0.1

In [36]:
pd.concat([df1, df2]) #por filas

a    b
0  8.2  9.7
1  6.7  4.1
2  8.2  5.6
2 -0.1 -0.6
3 -0.2 -0.6
4 -0.3 -0.1

In [37]:
pd.concat([df1, df2], axis=1) #por columnas compartiendo indices repetidos

a   b    a    b
0 8.2 9.7  NaN  NaN
1 6.7 4.1  NaN  NaN
2 8.2 5.6 -0.1 -0.6
3 NaN NaN -0.2 -0.6
4 NaN NaN -0.3 -0.1

In [38]:
pd.concat([df1, df2], axis=1, join='inner') # concatenacion solo de indices compartidos

a   b    a    b
2 8.2 5.6 -0.1 -0.6

In [39]:
pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis=1)

a   b    a    b
0 8.2 9.7 -0.1 -0.6
1 6.7 4.1 -0.2 -0.6
2 8.2 5.6 -0.3 -0.1

In [40]:
df1.append(df2)

a    b
0  8.2  9.7
1  6.7  4.1
2  8.2  5.6
2 -0.1 -0.6
3 -0.2 -0.6
4 -0.3 -0.1

In [41]:
df1.T.append(df2.T)

0   1    2    3    4
a 8.2 6.7  8.2  NaN  NaN
b 9.7 4.1  5.6  NaN  NaN
a NaN NaN -0.1 -0.2 -0.3
b NaN NaN -0.6 -0.6 -0.1